image : docker

services : 
    - docker: dind

stages :
    - test
    - deploy

test : 
    stage : test
    #specify in which branch this will triggers 
    only :
        - develop
        - production
    script :
        - echo run tests in this section

step-deploy-prod:
    stage : deploy
    only :
        - production
    script :
        - sudo apt-get install -y python-pip
        - pip install docker-compose
        - docker-compose up -d --build
    environement : production
    when : manual