# Official docker image.
image: docker:latest

services:
  - docker:dind

test:
  stage: build
  script:
    - docker build -t louis6docker/react-app -f Dockerfile.dev .
    - docker run -e CI=true louis6docker/react-app npm run test -- --coverage

  only:
    - develop

prod:
    stage: build
    script:
      - docker build -t registry.gitlab.com/louis6legros/react_app:latest .
      - docker push registry.gitlab.com/louis6legros/react_app:latest
    only:
      - production
      - master

