# Official docker image.
image: docker:latest

services:
  - docker:dind

before_script:
  - docker build -t louis6docker/react-app -f Dockerfile.dev .

test:
  stage: build
  script:
    - docker run -e CI=true louis6docker/react-app npm run test -- --coverage
  only:
    - master
