# Official docker image.
image: docker:latest

services:
  - docker:dind

variables:
    IMAGE_TAG: louis6docker/react-app:$CI_COMMIT_TAG
before_script:
  - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
test:
  stage: build
  script:
    - docker build -t $IMAGE_TAG -f Dockerfile.dev .
    - docker run -e CI=true $IMAGE_TAG npm run test -- --coverage

  only:
    - develop

prod:
    stage: build
    script:
      - docker build -t $IMAGE_TAG .
      - docker push $IMAGE_TAG
    only:
      - production
      - master

