sudo : required
services : 
    - docker

before_install : 
    - docker build -t louis6docker/noderedis -f Dockerfile.dev .

scirpt :
    - docker run -e CI=true louis6docker/noderedis npm run test -- --coverage


